### ISSUE TITLE
[bug] Updating PyPi version

### ISSUE THREAD

**Issue by lap1nou** [p0dalirius/DownloadPDBSymbols#7]
Hello,

Thank you for this amazing tool.

May I ask you if it's possible to update the version on PyPi ? The PyPi version doesn't seems to integrate fixes of #5 and #6.

Regards.

**Comment by p0dalirius** [comment]
Absolutely, this is a mistake I should have done it

**Comment by lap1nou** [comment]
No problem ^^, thank you very much.

**Comment by p0dalirius** [comment]
It is done :)

https://pypi.org/project/pdbdownload/1.3/
